swagger: "2.0"
info:
  description: >-
    Star wars interface server

  version: 1.0.0
  title: Star Wars Interface
  termsOfService: "[WIP]"
  contact:
    email: "test@email.com"
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: localhost:6868
basePath: /
tags:
  - name: search
    description: Some search results
  - name: recent
    description: Get various 'recent' items
  - name: bookmarks
    description: Your favorite star wars items
  - name: user
    description: Operations about user

schemes:
  - https
  - http
paths:
  /search:
    get:
      tags:
        - search
      summary: Get search results
      description: Returns an object containing results from official Swapi
      operationId: getResults
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      parameters:
        - name: category
          in: query
          description: Category used for making official request to SWAPI
          required: true
          type: string
          schema:
            $ref: "#/definitions/Pet"
        - name: input
          in: query
          description: Input String used for making official request to SWAPI
          required: true
          type: string
          schema:
            $ref: "#/definitions/Pet"
      responses:
        "405":
          description: Invalid input
        "200":
          description: Obj containing search results
          schema:
            type: object
            required:
              - data
            properties:
              results:
                type: array
  /recent:
    get:
      tags:
        - recent
      summary: Get various recent items eg. search terms or cached results
      description: Returns a list of 'recent' items
      operationId: getRecent
      produces:
        - application/xml
        - application/json
      parameters:
        - name: status
          in: query
          description: Status values that need to be considered for filter
          required: true
          type: array
          items:
            type: string
            enum:
              - available
              - pending
              - sold
            default: available
          collectionFormat: multi
      responses:
        "200":
          description: successful operation
          schema:
            type: array
            items:
              $ref: "#/definitions/Pet"
        "400":
          description: Invalid status value
      security:
        - petstore_auth:
            - "write:pets"
            - "read:pets"
